# About me

I'm an Assistant Professor in the [Rutgers Department of Linguistics][1], and
a member of the [Rutgers Center for Cognitive Science][2]. I'm a linguist and
a formal semanticist, which means that I study how humans pair linguistic form
with meaning from a formal (which is to say, mathematical) point of view.

My research looks at scope and binding, questions and indefiniteness, focus,
dynamic semantics, continuations and monads, ellipsis, and their interactions.
I'm interested in how developments in other disciplines (say, category theory
and computer science) can ground and enrich linguistic theory — see the
[Papers][3] tab for some recent examples. I spend a lot of time thinking about
how syntactic form constrains interpretation (and, occasionally, doesn't); I
have been both foe and friend to pseudo-scope mechanisms; I have a soft spot
for direct interpretation.

My website's being built right now. Not everything is populated just yet, and
not everything that's up is necessarily where or as it should be. But feel
free to poke around in the meantime.

[1]: http://ling.rutgers.edu
[2]: http://ruccs.rutgers.edu
[3]: http://simoncharlow.com/papers.html
