# About me

---

<div class="para">I'm an Assistant Professor in the [Rutgers Department of
Linguistics][1], and a member of the [Rutgers Center for Cognitive
Science][2]. I'm a linguist and a formal semanticist, which means that I study
how humans pair linguistic form with meaning from a formal (which is to say,
mathematical) point of view.

My research looks at scope and binding, questions and indefiniteness, focus,
dynamic semantics, continuations and monads, ellipsis, and their interactions.
I'm interested in how developments in other disciplines (say, category theory
and computer science) can ground and enrich linguistic theory — see the
[Papers][3] tab for some recent examples. I spend a lot of time thinking about
how syntactic form constrains interpretation (and, occasionally, doesn't).
I've been both foe and friend to pseudo-scope mechanisms. And I've got a soft
spot for direct interpretation.

<a href="img/me.jpg">Here</a> is a recent photo of me near the top of <a
href="https://en.wikipedia.org/wiki/Mount_Lemmon">Mount Lemmon</a>.

There should be a bit more here sometime soon. 🦉🦉🦉</div>

[1]: http://ling.rutgers.edu
[2]: http://ruccs.rutgers.edu
[3]: http://simoncharlow.com/papers.html
