# About me

---

<div class="para">I'm an Assistant Professor in the [Rutgers Department of
Linguistics][1], and a member of the [Rutgers Center for Cognitive
Science][2]. I'm a linguist and a formal semanticist, which means that I study
the mathematical structures that allow people to produce and understand
language. I started doing formal semantics at Brown University with <a
href="http://www.cog.brown.edu/People/jacobson/">Polly Jacobson</a>, and I got
my PhD at NYU working with <a
href="https://www.nyu.edu/projects/barker/">Chris Barker</a>.

My research looks at scope and binding, questions and indefiniteness, focus,
dynamic semantics, continuations and monads, ellipsis, and their interactions.
I'm interested in how developments in other disciplines (say, category theory
and computer science) can ground and enrich linguistic theory --- see the
[Papers][3] tab for some recent examples. I spend a lot of time thinking about
how syntactic form constrains interpretation (and, occasionally, doesn't).
I've been both foe and friend to pseudo-scope mechanisms. Given my background,
you might not be surprised to hear that I've got a soft spot for <a
href="https://global.oup.com/academic/product/direct-compositionality-9780199204380?cc=us&lang=en&">direct
interpretation</a>.

<a href="img/me.jpg">Here</a> is a recent photo of me near the top of <a
href="https://en.wikipedia.org/wiki/Mount_Lemmon">Mount Lemmon</a>.

There should be a bit more here sometime soon. 🦉🦉🦉</div>

[1]: http://ling.rutgers.edu
[2]: http://ruccs.rutgers.edu
[3]: http://simoncharlow.com/papers.html
