<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>$sitetitle$ - $pagetitle$</title>
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700|Megrim&subset=latin,greek-ext,latin-ext,greek"
          rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" media="screen"
          href="$root$css/screen.css">
    <link rel="stylesheet" type="text/css" media="print"
          href="$root$css/print.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"
            type="text/javascript"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script src="$root$js/nav.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="$root$css/screen.css" />
    <link rel="stylesheet" type="text/css" media="print" href="$root$css/print.css" />
  </head>
  <body>
    <div class="container-fluid">
      <header>
        <h1>$sitetitle$</h1>
      </header>
      <div class="row">
        <nav id="navbar" class="navbar nav navbar-default col-md-2">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle"
                    data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="navbar-collapse collapse">
            $nav$
          </div>
        </nav>
        <main role="main" class="col-md-10">
          $contents$
        </main>
      </div>
      <footer>
        powered by <a href="https://github.com/jgm/yst">yst</a>
      </footer>
    </div>


































<script type="text/javascript"> var sc_project=4801609; var sc_invisible=1; var sc_security="55f2a6bb"; var scJsHost = (("https:" == document.location.protocol) ? "https://secure." : "http://www."); document.write("<sc"+"ript type='text/javascript' src='" + scJsHost+ "statcounter.com/counter/counter.js'></"+"script>"); </script> <noscript><div class="statcounter"><a title="free hit counter" href="http://statcounter.com/" target="_blank"><img class="statcounter" src="//c.statcounter.com/4801609/0/55f2a6bb/1/" alt="free hit counter"></a></div></noscript><script type=text/javascript>var _gaq=_gaq||[];_gaq.push(["_setAccount","UA-36810337-1"]),_gaq.push(["_trackPageview"]),function(){var t=document.createElement("script");t.type="text/javascript",t.async=!0,t.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(t,c)}();</script>
  </body>
</html>
